// ═══════════════════════════════════════════════════════════════════════════
// RLU Municipiul Vaslui — Regulament Local de Urbanism
// Sursa: S.C. HABITAT PROIECT S.A. IAȘI, Contract nr. 15029/2003
//        Actualizare PUG Municipiul Vaslui, Vol. II RLU
// UrbanX TSS·FG | v1.0 | 2026-06-04
// ═══════════════════════════════════════════════════════════════════════════

(function () {
  if (!window.RLU_REGISTRY) window.RLU_REGISTRY = {};

  window.RLU_REGISTRY['vaslui'] = {

    meta: {
      name: 'Municipiul Vaslui',
      judet: 'VS',
      siruta: '171469',
      rluVersion: 'RLU Vaslui — Actualizare PUG 2003/2017',
      rluStatus: 'aprobat',
      elaborator: 'S.C. HABITAT PROIECT S.A. IAȘI',
      contract: '15029/2003',
      surse: ['RLU Vaslui Vol.II', 'PUG Vaslui Propuneri', 'CDR Planșe UTR 1-44'],
      dataCompletare: '2026-06-04',
      completatDe: 'TSS·FG',
      trupuri: ['Trup A (centru)', 'Trup A1', 'Trup A2', 'Trup A3', 'Trup B — Moara Grecilor', 'Trup C — Vișoara', 'Trup D', 'Trup E — Rediu', 'Trup F — Brodoc', 'Trup I'],
      seismic: { ag: 0.30, Tc: 0.7, zona: 'C', sursa: 'P100-1/2013, Tabel A1 (VASLUI, jud. VASLUI) — Tc corectat 26 iul (era 1.0, gresit; valoarea oficiala e 0.7)' },
      nota: 'UTR 6 și 29 — risc alunecare teren; interdicție temporară până la lucrări stabilizare versanți',
    },

    // ── Zone funcționale principale ──────────────────────────────────────
    zone: {
      'CC': {
        cod: 'CC', denumire: 'Zona Centrală — Centru Civic',
        culoare: '#C0392B',
        pot: 70, cut: 2.5, hMaxFloors: 7, hMaxM: 24,
        retragereStrada: 3, retragereVecin: 3,
        tip: 'centru-civic', tipLabel: 'Centru Civic și Administrativ',
        mixFunc: ['administrație publică', 'servicii publice', 'comerț', 'cultură', 'birouri', 'turism'],
        descriere: 'Zona centrală — centru civic, funcțiuni publice, administrative, comerciale și de servicii',
        utrs: [1],
      },
      'CM': {
        cod: 'CM', denumire: 'Zona Centrală Extinsă — Funcțiuni Mixte',
        culoare: '#E74C3C',
        pot: 65, cut: 2.0, hMaxFloors: 5, hMaxM: 18,
        retragereStrada: 3, retragereVecin: 3,
        tip: 'mixt-central', tipLabel: 'Centru Extins Mixt',
        mixFunc: ['locuire colectivă', 'comerț', 'servicii', 'birouri'],
        descriere: 'Zona centrală extinsă — funcțiuni mixte: locuire, comerț, servicii',
        utrs: [2, 3, 4, 24, 38],
      },
      'LA': {
        cod: 'LA', denumire: 'Locuințe Colective Mari — P+8÷P+10',
        culoare: '#F39C12',
        pot: 22, cut: 1.8, hMaxFloors: 11, hMaxM: 35,
        retragereStrada: 10, retragereVecin: 6,
        tip: 'rezidential-colectiv-mare', tipLabel: 'Rezidențial Colectiv P+8÷P+10',
        mixFunc: ['locuire colectivă', 'comerț parter max 200mp', 'dotări sociale cartier'],
        descriere: 'Ansambluri noi cu locuințe colective mari P+10; dotări de cartier la parter',
        utrs: [13, 37],
      },
      'Li': {
        cod: 'Li', denumire: 'Locuințe Individuale P+1-2',
        culoare: '#F1C40F',
        pot: 35, cut: 0.9, hMaxFloors: 3, hMaxM: 9,
        retragereStrada: 6, retragereVecin: 3,
        tip: 'rezidential-individual', tipLabel: 'Rezidențial Individual P+1-2',
        mixFunc: ['locuire individuală', 'comerț max 200mp Adc'],
        descriere: 'Zone locuințe individuale — case unifamiliale P+1-2, lotizare existentă sau nouă',
        utrs: [5, 7, 9, 10, 16, 18, 20, 23, 27, 29, 31, 35, 40, 41, 43, 44],
        conditii: 'Se admit funcțiuni comerciale și servicii profesionale max 200mp Adc dacă nu afectează liniștea zonei; comerțul se recomandă la intersecții',
        interzise: 'Industrie, activități productive poluante, service auto, depozitare en-gros, construcții provizorii',
      },
      'Lc': {
        cod: 'Lc', denumire: 'Locuințe Colective P+3÷P+8',
        culoare: '#E67E22',
        pot: 25, cut: 1.5, hMaxFloors: 6, hMaxM: 20,
        retragereStrada: 5, retragereVecin: 5,
        tip: 'rezidential-colectiv-mediu', tipLabel: 'Rezidențial Colectiv P+3÷P+8',
        mixFunc: ['locuire colectivă', 'comerț parter', 'servicii cartier'],
        descriere: 'Zone locuințe colective medii — blocuri P+3-P+8, dotări de cartier',
        utrs: [11, 22],
      },
      'AP': {
        cod: 'AP', denumire: 'Activități Productive — Industrie Mică, Depozitare, Servicii',
        culoare: '#8E44AD',
        pot: 55, cut: 1.2, hMaxFloors: 3, hMaxM: 12,
        retragereStrada: 6, retragereVecin: 5,
        tip: 'activitati-productive', tipLabel: 'Activități Productive și Servicii',
        mixFunc: ['industrie mică', 'depozitare', 'servicii productive', 'birouri administrative'],
        descriere: 'Zone activități productive — servicii, depozitare, mică industrie nepoluantă',
        utrs: [14, 25, 33, 39, 42],
        conditii: 'Perdea vegetală min 30m față de zone rezidențiale; studiu impact pentru activități cu risc tehnologic',
        interzise: 'Locuire, instituții publice sensibile, comerț en-gros cu substanțe periculoase',
      },
      'IS': {
        cod: 'IS', denumire: 'Zona Industrială — Platformă Industrială și Servicii',
        culoare: '#6C3483',
        pot: 65, cut: 2.0, hMaxFloors: null, hMaxM: 18,
        retragereStrada: 8, retragereVecin: 6,
        tip: 'industrial', tipLabel: 'Zonă Industrială și Servicii',
        mixFunc: ['industrie', 'depozitare', 'servicii productive', 'logistică'],
        descriere: 'Platforme industriale, hale, depozite, infrastructură de producție',
        utrs: [15, 26, 32],
        conditii: 'POT și CUT pentru obiective noi se stabilesc prin studii de specialitate; aviz mediu obligatoriu',
        interzise: 'Locuire, instituții publice, comerț cu amănuntul general',
      },
      'Sp': {
        cod: 'Sp', denumire: 'Zona Spații Verzi și Agrement',
        culoare: '#27AE60',
        pot: 5, cut: 0.05, hMaxFloors: 1, hMaxM: 6,
        retragereStrada: null, retragereVecin: null,
        tip: 'spatii-verzi', tipLabel: 'Spații Verzi, Sport și Agrement',
        mixFunc: ['parcuri', 'agrement', 'sport', 'protecție versanți', 'protecție curs apă'],
        descriere: 'Parcuri, lacuri, zone de recreere, amenajări sportive, fâșii de protecție',
        utrs: [6, 12, 19, 28, 36],
        nota: 'UTR 6 și 29 — risc alunecare; UTR 28 — fâșie de protecție 30m față de albia râului Bârlad',
      },
      'Ag': {
        cod: 'Ag', denumire: 'Zona Activități Agricole și Agro-Zootehnice',
        culoare: '#A9CCE3',
        pot: 20, cut: 0.3, hMaxFloors: 1, hMaxM: 8,
        retragereStrada: null, retragereVecin: null,
        tip: 'agricol', tipLabel: 'Activități Agricole și Agro-Zootehnice',
        mixFunc: ['ferme', 'sere', 'exploatații agricole', 'mecanizare agricolă'],
        descriere: 'Zone activități agricole — ferme, sere, exploatații, culturi',
        utrs: [17, 21, 30, 34],
        conditii: 'Zone de protecție sanitară obligatorii față de zone rezidențiale conform RLU',
      },
      'TE': {
        cod: 'TE', denumire: 'Zona Tehnico-Edilitară',
        culoare: '#7F8C8D',
        pot: 50, cut: 1.0, hMaxFloors: 2, hMaxM: 9,
        retragereStrada: null, retragereVecin: null,
        tip: 'tehnico-edilitar', tipLabel: 'Infrastructură Tehnico-Edilitară',
        mixFunc: ['infrastructură', 'depozite tehnice', 'stații tehnice'],
        descriere: 'Infrastructură tehnico-edilitară — stații, depozite, servicii tehnice',
        utrs: [8],
      },
    },

    // ── Reguli generale RLU Vaslui (extras Vol. II) ───────────────────────
    reguliGenerale: {
      aliniament: {
        profil1: 'aliniere la aliniamentul clădirilor existente',
        profil2_3: 'retragere 8.0m față de aliniament general',
        stradaNeclasata: '8.0m față de axul drumului',
        nota: 'Retragere față de aliniament permisă doar dacă respectă coerența fronturilor stradale',
      },
      distanteProtectie: {
        albieMinora: 30,
        cimitire: 50,
        caiFerate: 100,
        linieElectrica20kV: 24,
        linieElectrica110kV: 36,
        magistralaGaze: 50,
        statieEpurare: 300,
        obor: 500,
        statieMeteo: 30,
        platDepozitareGunoi: 1000,
      },
      interdictiiGenerale: [
        'Zone cu risc alunecare (UTR 6, 29; loc. Bahnari UTR2; loc. Brodoc UTR3,4; loc. Rediu UTR1,3,5) — interdicție temporară până la stabilizare versanți',
        'Zona de protecție CF (100m de la limita zonei cadastrale CF) — până la aviz SNCFR',
        'Zone cu destinație specială — până la aviz ministere de resort',
        'Zona de protecție a albiei minore (30m)',
        'Zona de protecție a liniei electrice 20kV (12m din ax)',
        'Zona de protecție a liniei electrice 110kV (25m din ax)',
        'Zona de protecție a magistralei de gaze naturale (25m din ax)',
      ],
      mansardare: 'Se admite mansardarea — în calcul CUT se adaugă 60% din aria unui nivel curent',
    },

    // ── UTR-uri complete (44) ─────────────────────────────────────────────
    utrs: {
      1:  { zona: 'CC',  denumire: 'Centru Civic',              trup: 'A',   pot: 70,  cut: 2.5,  hm: 24, regim: 'P+2-P+6', sup_ha: 45  },
      2:  { zona: 'CM',  denumire: 'Centru Extins Vest',        trup: 'A',   pot: 65,  cut: 2.0,  hm: 18, regim: 'P+1-P+4', sup_ha: 38  },
      3:  { zona: 'CM',  denumire: 'Centru Extins Nord',        trup: 'A',   pot: 65,  cut: 2.0,  hm: 18, regim: 'P+1-P+4', sup_ha: 42  },
      4:  { zona: 'CM',  denumire: 'Zona Mixtă Nord',           trup: 'A',   pot: 55,  cut: 1.6,  hm: 15, regim: 'P+2-P+4', sup_ha: 28  },
      5:  { zona: 'Li',  denumire: 'Locuințe Individuale Nord', trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 95  },
      6:  { zona: 'Sp',  denumire: 'Agrement — Lacul Roșu',    trup: 'A',   pot: 5,   cut: 0.05, hm: 6,  regim: '—',        sup_ha: 35, nota: 'RISC ALUNECARE — interdicție temporară construcții' },
      7:  { zona: 'Li',  denumire: 'Locuințe Est — Dealul Viei',trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 68  },
      8:  { zona: 'TE',  denumire: 'Activități Tehnico-Edilitare Est', trup: 'A', pot: 50, cut: 1.0, hm: 9, regim: 'P-P+1', sup_ha: 22 },
      9:  { zona: 'Li',  denumire: 'Locuințe Est II',           trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 72  },
      10: { zona: 'Li',  denumire: 'Locuințe Est III',          trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 58  },
      11: { zona: 'Lc',  denumire: 'Locuințe Colective Sud-Est',trup: 'A',   pot: 25,  cut: 1.5,  hm: 17, regim: 'P+3-P+5', sup_ha: 40  },
      12: { zona: 'Sp',  denumire: 'Zona Verde Sud-Est',        trup: 'A',   pot: 5,   cut: 0.05, hm: 6,  regim: '—',        sup_ha: 48, nota: 'Destinație specială S' },
      13: { zona: 'LA',  denumire: 'Locuințe Colective Nord',   trup: 'A',   pot: 22,  cut: 1.8,  hm: 35, regim: 'P+4-P+8', sup_ha: 35  },
      14: { zona: 'AP',  denumire: 'Activități Productive Nord',trup: 'A',   pot: 60,  cut: 1.5,  hm: 12, regim: 'P-P+2',   sup_ha: 52  },
      15: { zona: 'IS',  denumire: 'Industrie Nord-Vest',       trup: 'A',   pot: 65,  cut: 2.0,  hm: 18, regim: 'P-P+3',   sup_ha: 88  },
      16: { zona: 'Li',  denumire: 'Locuințe Individuale Vest', trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 62  },
      17: { zona: 'Ag',  denumire: 'Activități Agro-Zoo Nord',  trup: 'A1',  pot: 20,  cut: 0.3,  hm: 8,  regim: 'P',        sup_ha: 120 },
      18: { zona: 'Li',  denumire: 'Locuințe Individuale NV',   trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 55  },
      19: { zona: 'Sp',  denumire: 'Sport și Agrement',         trup: 'A',   pot: 15,  cut: 0.3,  hm: 6,  regim: 'P-P+1',   sup_ha: 30  },
      20: { zona: 'Li',  denumire: 'Locuințe Sud',              trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 78  },
      21: { zona: 'Ag',  denumire: 'Zona Agricolă Sud',         trup: 'A',   pot: 5,   cut: 0.05, hm: 0,  regim: '—',        sup_ha: 200 },
      22: { zona: 'Lc',  denumire: 'Locuințe Colective Vest',   trup: 'A',   pot: 25,  cut: 1.5,  hm: 17, regim: 'P+3-P+5', sup_ha: 32  },
      23: { zona: 'Li',  denumire: 'Locuințe Individuale SV',   trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 65  },
      24: { zona: 'CM',  denumire: 'Centru Extins Vest II',     trup: 'A',   pot: 60,  cut: 1.8,  hm: 15, regim: 'P+1-P+3', sup_ha: 40  },
      25: { zona: 'AP',  denumire: 'Activități Productive Vest',trup: 'A',   pot: 55,  cut: 1.2,  hm: 12, regim: 'P-P+2',   sup_ha: 45  },
      26: { zona: 'IS',  denumire: 'Industrie Vest',            trup: 'A',   pot: 65,  cut: 2.0,  hm: 18, regim: 'P-P+3',   sup_ha: 75  },
      27: { zona: 'Li',  denumire: 'Locuințe Individuale V',    trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 80  },
      28: { zona: 'Sp',  denumire: 'Zona Verde Râul Bârlad',    trup: 'A',   pot: 5,   cut: 0.05, hm: 6,  regim: '—',        sup_ha: 25, nota: 'Fâșie protecție 30m râul Bârlad' },
      29: { zona: 'Li',  denumire: 'Trup A2 — Vest',            trup: 'A2',  pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 55, nota: 'RISC ALUNECARE — interdicție temporară' },
      30: { zona: 'Ag',  denumire: 'Activități Agro NE',        trup: 'A',   pot: 20,  cut: 0.3,  hm: 8,  regim: 'P',        sup_ha: 95  },
      31: { zona: 'Li',  denumire: 'Locuințe Individuale S',    trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 48  },
      32: { zona: 'IS',  denumire: 'Industrie Sud-Vest',        trup: 'A2',  pot: 65,  cut: 1.8,  hm: 12, regim: 'P-P+2',   sup_ha: 60  },
      33: { zona: 'AP',  denumire: 'Activități Prod. SV',       trup: 'A2',  pot: 55,  cut: 1.2,  hm: 12, regim: 'P-P+2',   sup_ha: 38, nota: 'Teren rezervat parțial pentru locuințe sociale P+3-4' },
      34: { zona: 'Ag',  denumire: 'Zona Agricolă NE',          trup: 'A',   pot: 5,   cut: 0.05, hm: 0,  regim: '—',        sup_ha: 180 },
      35: { zona: 'Li',  denumire: 'Locuințe Est IV',           trup: 'A',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 85  },
      36: { zona: 'Sp',  denumire: 'Zona Verde Delea',          trup: 'A',   pot: 5,   cut: 0.05, hm: 6,  regim: '—',        sup_ha: 18, nota: 'Pârâul Delea — protecție curs apă' },
      37: { zona: 'LA',  denumire: 'Locuințe Colective E',      trup: 'A',   pot: 22,  cut: 1.8,  hm: 28, regim: 'P+4-P+8', sup_ha: 30  },
      38: { zona: 'CM',  denumire: 'Zona Mixtă NE',             trup: 'A',   pot: 50,  cut: 1.5,  hm: 12, regim: 'P+1-P+3', sup_ha: 35  },
      39: { zona: 'AP',  denumire: 'Activități Prod. N',        trup: 'A',   pot: 55,  cut: 1.2,  hm: 12, regim: 'P-P+2',   sup_ha: 42  },
      40: { zona: 'Li',  denumire: 'Trup I — Nou',              trup: 'I',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 28  },
      41: { zona: 'Li',  denumire: 'Trup B — Moara Grecilor',   trup: 'B',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 95  },
      42: { zona: 'AP',  denumire: 'Trup B — Activități',       trup: 'B',   pot: 50,  cut: 1.0,  hm: 6,  regim: 'P-P+1',   sup_ha: 30  },
      43: { zona: 'Li',  denumire: 'Trup C — Vișoara',          trup: 'C',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 45  },
      44: { zona: 'Li',  denumire: 'Trup E — Rediu',            trup: 'E',   pot: 35,  cut: 0.9,  hm: 9,  regim: 'P+1-P+2', sup_ha: 65  },
    },
  };

  console.log('[RLU_REGISTRY] ✅ Vaslui înregistrat — 44 UTR-uri, 10 zone funcționale');
})();
